---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY
    time_format: ''
    export_format: YYYY
    display_utc: true
  default: now
  hidden: false
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- journal/my-new-event.md
- projects/a-dream-of-spring.md
- projects/about.md
- projects/above-and-beyond.md
- projects/above-water.md
- projects/back.md
- projects/blooming-peony.md
- projects/canvas-1.md
- projects/canvas-11.md
- projects/canvas-2.md
- projects/canvas-3.md
- projects/canvas-4.md
- projects/canvas-5.md
- projects/canvas-6.md
- projects/canvas-7.md
- projects/canvas-8.md
- projects/canvas-9.md
- projects/faces.md
- projects/flowers-in-the-middle-of-snowflakes.md
- projects/heaven-is-under-your-feet.md
- projects/ice-eyes.md
- projects/lazy-afternoon.md
- projects/morning-rituals.md
- projects/oil-n-gold-l.md
- projects/provocation.md
- projects/reproduction-1.md
- projects/reproduction-10.md
- projects/reproduction-11.md
- projects/reproduction-13.md
- projects/reproduction-2-1.md
- projects/reproduction-3-1.md
- projects/reproduction-4-1.md
- projects/reproduction-5-1.md
- projects/reproduction-6.md
- projects/reproduction-7.md
- projects/reproduction-8.md
- projects/reproduction-9.md
- projects/smells-like-summer-2.md
- projects/smells-like-summer.md
