---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY
    time_format: ''
    export_format: YYYY
    display_utc: true
  default: now
  hidden: false
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- projects/print-1.md
- projects/canvas-11.md
- projects/canvas-10.md
- projects/canvas-9.md
- projects/canvas-8.md
- projects/canvas-7.md
- projects/canvas-6.md
- projects/canvas-5.md
- projects/canvas-4.md
- projects/canvas-3.md
- projects/canvas-2.md
- projects/canvas-1.md
- projects/bang-bang.md
- projects/reproduction-5.md
- projects/reproduction-4.md
- projects/reproduction-3.md
- projects/reproduction-2.md
- projects/reproduction-1.md
- journal/my-new-event.md
- projects/water-colors.md
- projects/oil-n-gold-l.md
