---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY
    time_format: ''
    export_format: YYYY
    display_utc: true
  default: now
  hidden: false
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
pages:
- projects/bang-bang.md
- projects/water-colors.md
- projects/oil-n-gold-l.md
- projects/chelsea-landmark.md
